.TH YED-AUTO_PAREN 7 "YED Plugin Manuals" "" "YED Plugin Manuals"
.SH NAME
auto_paren \- automatically adds the matching character to these [({'"
.SH CONFIGURATION
.SS disable-auto-paren   "  " [ yes / no ]
disables the automatic insert of a following )
.SS disable-auto-bracket ""   [ yes / no ]
disables the automatic insert of a following ]
.SS disable-auto-dquote  " "  [ yes / no ]
disables the automatic insert of a following "
.SS disable-auto-quote   "  " [ yes
disables the automatic insert of a following '
.SS disable-auto-brace   "  " [ yes / no ]
disables the automatic insert of a following }
.SS auto-paren-skip      "  " [ yes / no ]
if set you will be able to skip ]}) no matter where you are in the file
.SS auto-dquote-skip     "  " [ yes / no ]
if set you will be able to skip " no matter where you are in the file
.SS auto-quote-skip      "  " [ yes / no ]
if set you will be able to skip ' no matter where you are in the file
.SS auto-paren-jump_word "  " [ yes / no ]
if set you will be able to move the )]} to the right side of the connected word
.SS auto-dquote-jump_word "  " [ yes / no ]
if set you will be able to move the " to the right side of the connected word
.SS auto-quote-jump_word "  " [ yes / no ]
if set you will be able to move the ' to the right side of the connected word
.SH COMMANDS
None
.SH BUFFERS
None
.SH NOTES
.P
Automatically adds the correct following character to the one inserted.
Auto split and indention has been added to ([{ when you hit enter.
.SH VERSION
0.0.1
.SH KEYWORDS
automatic, parenthesis, brackets, braces, single quotes, double quotes, finish
