.TH YED-BRACE_HL 7 "YED Plugin Manuals" "" "YED Plugin Manuals"
.SH NAME
brace_hl \- Highlight matching curly braces.
.SH CONFIGURATION
.SS brace-hl-max-line-length
When scanning for matching braces, if a line exceeds brace-hl-max-line-length, stop scanning.
.SH COMMANDS
None
.SH BUFFERS
None
.SH NOTES
Uses the "attention" style component.
.SH VERSION
0.0.1
.SH KEYWORDS
highlight, curly, brace, braces, match
