.TH YED-COMMAND-HISTORY 7 "YED Plugin Manuals" "" "YED Plugin Manuals"
.SH NAME
command-history \- Saves commands between one use of YED and another.
.SH CONFIGURATION
.SS command-history-limit <limit>
The number of commands to be saved for command history. The maximum allowed is 10,000.
.SH COMMANDS
None
.SH BUFFERS
None
.SH NOTES
.P
The file that this plugin uses to store the command history is ~/.config/yed/my-command-history.txt.
.SH VERSION
0.0.1
.SH KEYWORDS
save, command, history
