.TH YED-CONFIRM-QUIT 7 "YED Plugin Manuals" "" "YED Plugin Manuals"
.SH NAME
confirm-quit \- Check for unsaved buffers before quitting.
.SH CONFIGURATION
None
.SH COMMANDS
.SS no-confirm-quit
Force quit without checking for modified buffers. Changed in unsaved buffers will be lost.
.SH NOTES
This overrides the built-in quit command.
.SH VERSION
0.0.2
.SH KEYWORDS
quit, confirm, save, write, modified
