.TH YED-ADD_TEMPLATE 7 "YED Plugin Manuals" "" "YED Plugin Manuals"
.SH NAME
add_template \- pastes the specified template at the cursor location
.SH CONFIGURATION
None
.SH COMMANDS
.SS set-template [ template-name ]
When this command is run the template that is passed will be pasted at the current cursor location
.SH BUFFERS
None
.SH NOTES
.P
The user must add templates to the ~/.yed/templates dir. The files must be named in this style [template-name.txt].
.SH VERSION
0.0.1
.SH KEYWORDS
template, block paste
