.TH YED-CUSTOM_FRAMES 7 "YED Plugin Manuals" "" "YED Plugin Manuals"
.SH NAME
custom_frames \- Gives a configurable framework to attach custom frames and special animations to special buffers
.SH CONFIGURATION
.SS see commands
.SH COMMANDS
.SS set-custom-buffer-frame (frame-name[""]) (split/float['f']) (close-after[0/1]) (max-x[0.0/1.0]) (max-y[0.0/1.0]) (max-width[0.0/1.0]) (max-height[0.0/1.0])
                    (use-animation[0/1]) (min-x[0.0/1.0]) (min-y[0.0/1.0]) (min-width[0.0/1.0]) (min-height[0.0/1.0]) (speed[int]) (buff-arr["*buff *buff *buff"])
.SS set-custom-buffer-frame (frame-name[""]) (split/float['s']) (close-after[0/1]) (max-split['h'/'v']) (max-loc[('t'/'b')/('l'/'r')]) (max-use-root['r'/'a'])
                    (max-size[0.0/1.0]) (max-heirarchy[int]) (use-animation[0/1]) (min-size[0.0/1.0]) (speed[int]) (buff-arr["*buff *buff *buff"])
.SS special-buffer-prepare-focus "*buffer_name"
.SS special-buffer-prepare-jump-focus "*buffer_name"
.SS special-buffer-prepare-unfocus "*buffer_name"

.SH BUFFERS
None
.SH NOTES
.P This plugin overrides three core YED functions, special-buffer-prepare-focus special-buffer-prepare-jump-focus and special-buffer-prepare-unfocus.
The way that you use this plugin is as follows. Add a configuration line in your yedrc for every frame that you want to behave a certain way.
You then can set up the parameters of how that frame should function and then what buffers you want to open in that type of frame. I will describe
the parameters now.
.SS frame-name: {""} The new frame's name.
.SS split/float: {'s' / 'f'} Wether you want the new frame to be a split of a frame or a new "floating" frame.
.SS close-after: {0 / 1} Wether you want to close the frame when another frame is activated.
.SS --------------------
.SS if split/float == 'f'
.SS max-x: {0.0 / 1.0} The starting x position of the "full sized" frame. 0.0 is far left and 1.0 is far right.
.SS max-y: {0.0 / 1.0} The starting y position of the "full sized" frame. 0.0 is far left and 1.0 is far right.






.P The first is the frame-name and it is taken in as a string. The second is where the config splits in two directions, you can choose
either a floating style frame that is not attached to anything else, or you may choose a split of a frame. I will talk about floating frames first. The
third parameter decides wether to close the frame or not after making the frame not the active frame. The next four parameters decide the bounding box of
the "max/normal" size of the frame. 0.0/0.0 is the top left and 1.0/1.0 is the bottom right of the space for x and y, width and height work the same way.
The animation flag sets wether or not for the frame to animate when opening/closing/going between active and not. If you do not want the frame to animate then
the next 4 parameters describe here are unnecisary but they are the minimum size of the frame when deactivated. The next is also unnecisarry if no animations
are used but is the speed at which then frame will animate in hz or screen updates/second. The last parameter is a space separated string of all the special
buffers that you want to apply to this frame. The next section will talk about the splits. If split is chosen then you can either pick a 'h'=horizontal/'v'=vertical
split then next parameter decides which frame of the split to put the buffer in. If you choose 'v' then you can choose between 'l'=left/'r'=right side and if you
choose 'h' then you can choose between 't'=top/'b'=bottom. The next parameter lets you choose where to split the frame from, either the root frame or the
active frame. The best way to understand this is that if the root frame is chosen the frames with work the exact same way everytime, more or less. The next parameter
is the "max/normal" size of the frame in terms of width or height based on wether you chose 'v'/'h'. The last different parameter is heirarchy this is a integer
0-9999 that describes a way for one split to supercede or use the full frame over another. If a frame has a smaller number then it is more important that another
and will overlap larger number ones.
.SH VERSION
0.0.1
.SH KEYWORDS
custom_frames, custom, frame, special, buffers, animations
