.TH YED-diff 7 "YED Plugin Manuals" "" "YED Plugin Manuals"
.SH NAME
diff \- interactive diff for two buffers
.SH CONFIGURATION
.SS diff-multi-line-compare-algorithm "" [ "myers" / "myers_linear" / ("patience")]
sets the algorithm for comparing the file line by line

.SS diff-line-compare-algorithm "      " [ "myers" / "myers_linear" / ("patience")]
sets the algorithm for comparing two like lines in the file

.SS diff-insert-color "                " [ &active &blue swap ]
sets the background color for an inserted line

.SS diff-insert-dashes-color "         " [ &active &cyan swap ]
sets the background color for the inserted dashed line opposite an insert

.SS diff-delete-color "                " [ &active &blue swap ]
sets the background color for a deleted line

.SS diff-delete-dashes-color "         " [ &active &cyan swap ]
sets the background color for the inserted dashed line opposite a delete

.SS diff-inner-compare-color "         " [ &active &magenta swap ]
sets the background color two lines that are close to the same

.SS diff-inner-compare-char-color "    " [ &active &attention swap ]
sets the background color for the characters that are inserted/deleted in the lines that are close (inner-compare)

.SS diff-truncate-lines "              " [ (yes) / no ]
if you want to truncate lines that are the same between both files

.SS diff-truncate-lines-min-num "      " [ 12 ]
the minimum number of lines that need to be the same contiguously before truncation starts

.SS diff-truncate-color "              " [ &active &cyan ]
the color of the added line showing the number of lines that has been truncated in this section

.SH COMMANDS
.SS diff(buffer1, buffer2) interactive diff for two buffers
.SH BUFFERS
.SS diff:buffer1 -- a buffer used by diff so that the original is not mutated
.SS diff:buffer2 -- a buffer used by diff so that the origianl is not mutated
.SH NOTES
.SS If you want to run this command from the terminal insert this into you .bashrc
.SS function yeddiff { yed -c \/"diff $1 $2\/"; }
.SH VERSION
0.0.1
.SH KEYWORDS
diff, yeddiff, compare
