.TH YED-DRILL 7 "YED Plugin Manuals" "" "YED Plugin Manuals"
.SH NAME
drill \- Modal editing a la kakoune, but lamer.
.SH CONFIGURATION
None
.SH COMMANDS
.SS drill-bind <mode> <keys> <command>
Bind <keys> to <command> when in <mode>.
.SS drill-unbind <mode> <keys>
Unbind <keys> in <mode>.
.SS drill-exit-insert
Leave insert mode and return to normal mode.
.SS w
.SS W
Alias for write-buffer.
.SS q
.SS Q
If you're in the only frame, quit.
Otherwise, close the frame.
.SS wq
.SS Wq
write-buffer, then do q from above.
.SH BUFFERS
None
.SH NOTES
.SS Recommended config
bind "ctrl-o" jump-stack-pop

drill-bind normal "g d" multi jump-stack-push ctags-jump-to-definition

drill-bind normal "g e" 'cursor-buffer-end'

drill-bind normal "g g" 'cursor-buffer-begin'

.SH VERSION
1000.0.1
.SH KEYWORDS
key, bind, binding, edit, mode, modal, vim, vi, emacs
