.TH YED-EXTENSION_MAPPER 7 "YED Plugin Manuals" "" "YED Plugin Manuals"
.SH NAME
extension_mapper \- Map file extensions to file types.
.SH CONFIGURATION
None
.SH COMMANDS
.SS map-extension EXT FT
Assign file type FT to buffers with extension EXT.
.SH NOTES
The file type must exist.

Examples:
    map-extension CC C++
    map-extension json Config
.SH VERSION
0.0.1
.SH KEYWORDS
file, type, ft, map, extension, name
