.TH YED-FIND_BRACKET 7 "YED Plugin Manuals" "" "YED Plugin Manuals"
.SH NAME
find_bracket \- finds the connecting bracket to the on you are on
.SH CONFIGURATION
None
.SH COMMANDS
.SS brace-goto-other
When the cursor is on a brace, this command finds the brace that connects to it and moves the cursor there.
.SH BUFFERS
None
.SH NOTES
.P
This plugin is much like the % command in vim.
.SH VERSION
0.0.1
.SH KEYWORDS
bracket, goto, find
