.TH YED-GIT_VARIABLES 7 "YED Plugin Manuals" "" "YED Plugin Manuals"
.SH NAME
git_variables \- A plugin that makes variables for your current git repository properties
.SH CONFIGURATION
.SS git-variables-update-interval " " [positive int miliseconds]
Milisecond interval to update on.
.SS git-variables-branch-icon " " [string]
String to append to the beginning of the branch variable.
.SH COMMANDS
None
.SH BUFFERS
None
.SH NOTES
Creates variable git-variables-branch which contains the current branch name.Also creates git-variables-repo-name with the repository name.
.SH VERSION
0.0.1
.SH KEYWORDS
git status
