.TH YED-LANG-SYNTAX-JAVASCRIPT 7 "YED Plugin Manuals" "" "YED Plugin Manuals"
.SH NAME
lang/syntax/javascript \- Syntax highlighting for the JavaScript filetype.
.SH CONFIGURATION
None
.SH COMMANDS
None
.SH BUFFERS
None
.SH NOTES
None
.SH VERSION
0.0.2
.SH KEYWORDS
lang, language, filetype, file, syntax, highlight, javascript, JavaScript
