.TH YED-LANG-C 7 "YED Plugin Manuals" "" "YED Plugin Manuals"
.SH NAME
lang/scheme \- Filetype for Go.
.SH CONFIGURATION
None
.SH COMMANDS
None
.SH BUFFERS
None
.SH NOTES
The filetype is called "Go".
Matches the file extensions .go.
.SH VERSION
0.0.1
.SH KEYWORDS
lang, language, filetype, file, type, go, golang, google
