.TH YED-LANG-SYNTAX-S 7 "YED Plugin Manuals" "" "YED Plugin Manuals"
.SH NAME
lang/syntax/s \- Syntax highlighting for the S filetype.
.SH CONFIGURATION
None
.SH COMMANDS
None
.SH BUFFERS
None
.SH NOTES
None
.SH VERSION
0.0.1
.SH KEYWORDS
lang, language, filetype, file, syntax, highlight, s, assembly, asm
