.TH YED-LANG-BPFTRACE 7 "YED Plugin Manuals" "" "YED Plugin Manuals"
.SH NAME
lang/s \- Filetype for bpftrace files.
.SH CONFIGURATION
.SS lang-bpftrace-extensions: a space separated string of all extensions that are considered a bpftrace file.
.SH COMMANDS
None
.SH BUFFERS
None
.SH NOTES
The filetype is called "S".
Matches buffer names *.S
.SH VERSION
0.0.1
.SH KEYWORDS
lang, language, filetype, file, type, bpf, ebpf, bfptrace
