.TH YED-LANG-LINKER 7 "YED Plugin Manuals" "" "YED Plugin Manuals"
.SH NAME
lang/linker \- Filetype for linker scripts.
.SH CONFIGURATION
None
.SH COMMANDS
None
.SH BUFFERS
None
.SH NOTES
The filetype is called "Linker".
Matches file extension .lds.
.SH VERSION
0.0.1
.SH KEYWORDS
lang, language, filetype, file, type, ld, lds, linker, script
