.TH YED-LANG-SYNTAX-DIFF_HL 7 "YED Plugin Manuals" "" "YED Plugin Manuals"
.SH NAME
lang/syntax/diff_hl \- Syntax highlighting for the diff files.
.SH CONFIGURATION
.SS diff-hl-on "     " [ yes / no ]
.SS diff-hl-location the color to highlight the location line, defaults to "fg !6"
.SS diff-hl-add "    " the color to highlight the add line, defaults to "fg !2"
.SS diff-hl-remove " " the color to highlight the remove line, defaults to "fg !1"
.SH COMMANDS
None
.SH BUFFERS
None
.SH NOTES
None
.SH VERSION
0.0.1
.SH KEYWORDS
syntax, highlight, diff
