.TH YED-LANG-SYNTAX-NIX 7 "YED Plugin Manuals" "" "YED Plugin Manuals"
.SH NAME
lang/syntax/nix \- Syntax highlighting for the Nix filetype.
.SH CONFIGURATION
None
.SH COMMANDS
None
.SH BUFFERS
None
.SH NOTES
None
.SH VERSION
None
1000.\&01
.SH KEYWORDS
lang, language, filetype, file, syntax, highlight, nix
