.TH YED-LANG-SYNTAX-LINKER 7 "YED Plugin Manuals" "" "YED Plugin Manuals"
.SH NAME
lang/syntax/linker \- Syntax highlighting for the Linker filetype.
.SH CONFIGURATION
None
.SH COMMANDS
None
.SH BUFFERS
None
.SH NOTES
None
.SH VERSION
0.0.1
.SH KEYWORDS
lang, language, filetype, file, syntax, highlight, ld, lds, linker, script
