.TH YED-LANG-SYNTAX-C 7 "YED Plugin Manuals" "" "YED Plugin Manuals"
.SH NAME
lang/syntax/csharp \- Syntax highlighting for the Go filetype.
.SH CONFIGURATION
None
.SH COMMANDS
None
.SH BUFFERS
None
.SH NOTES
None
.SH VERSION
0.0.1
.SH KEYWORDS
lang, language, filetype, file, syntax, highlight, go, golang, google
