.TH YED-LANG-SYNTAX-SIMON 7 "YED Plugin Manuals" "" "YED Plugin Manuals"
.SH NAME
lang/syntax/simon \- Syntax highlighting for the Simon filetype.
.SH CONFIGURATION
None
.SH COMMANDS
None
.SH BUFFERS
None
.SH NOTES
None
.SH VERSION
0.0.1
.SH KEYWORDS
lang, language, filetype, file, syntax, highlight, simon, si
