.TH YED-LANG-SYNTAX-MAKE 7 "YED Plugin Manuals" "" "YED Plugin Manuals"
.SH NAME
lang/syntax/make \- Syntax highlighting for the Make filetype.
.SH CONFIGURATION
None
.SH COMMANDS
None
.SH BUFFERS
None
.SH NOTES
None
.SH VERSION
0.0.1
.SH KEYWORDS
lang, language, filetype, file, syntax, highlight, make, makefile, Makefile
