.TH YED-LANG-SYNTAX-MAN 7 "YED Plugin Manuals" "" "YED Plugin Manuals"
.SH NAME
lang/syntax/man \- Syntax highlighting for the Man filetype.
.SH CONFIGURATION
None
.SH COMMANDS
None
.SH BUFFERS
None
.SH NOTES
None
.SH VERSION
0.0.1
.SH KEYWORDS
lang, language, filetype, file, syntax, highlight, man, manpage, troff, groff
