.TH YED-LANG-SYNTAX-GO 7 "YED Plugin Manuals" "" "YED Plugin Manuals"
.SH NAME
lang/syntax/go \- Syntax highlighting for the Go filetype.
.SH CONFIGURATION
None
.SH COMMANDS
None
.SH BUFFERS
None
.SH NOTES
None
.SH VERSION
None
1000.\&01
.SH KEYWORDS
lang, language, filetype, file, syntax, highlight, go
