.TH YED-LANG-SYNTAX-BPFTRACE 7 "YED Plugin Manuals" "" "YED Plugin Manuals"
.SH NAME
lang/syntax/bpftrace \- Syntax highlighting for the bpftrace filetype.
.SH CONFIGURATION
None
.SH COMMANDS
None
.SH BUFFERS
None
.SH NOTES
None
.SH VERSION
0.0.1
.SH KEYWORDS
lang, language, filetype, file, syntax, highlight, bpf, ebpf, bpftrace
