.TH YED-LANG-YAML 7 "YED Plugin Manuals" "" "YED Plugin Manuals"
.SH NAME
lang/yaml \- Filetype for YAML files.
.SH CONFIGURATION
.SS lang-yaml-extensions: a space separated string of additional extensions that are considered a YAML file.
.SH COMMANDS
None
.SH BUFFERS
None
.SH NOTES
The filetype is called "YAML".
Matches buffer names *.yaml and *.yml by default.
.SH VERSION
0.0.1
.SH KEYWORDS
lang, language, filetype, file, type, yaml, yml
