.TH YED-LANG-SYNTAX-JULE 7 "YED Plugin Manuals" "" "YED Plugin Manuals"
.SH NAME
lang/syntax/jule \- Syntax highlighting for the Jule filetype.
.SH CONFIGURATION
None
.SH COMMANDS
None
.SH BUFFERS
None
.SH NOTES
None
.SH VERSION
0.0.1
.SH KEYWORDS
lang, language, filetype, file, syntax, highlight, jule, Jule, lisp, LISP, justified
