.TH YED-LANG-TOOLS-GO 7 "YED Plugin Manuals" "" "YED Plugin Manuals"
.SH NAME
lang/tools/go \- Allows for auto formatting in a Go file.
.SH CONFIGURATION
gofmt-auto <"yes|no"> - Automatically format buffers, off by default.\&
.SH COMMANDS
.SS go-fmt 
Run go-fmt to auto format the buffer in the active frame.
.SH BUFFERS
None
.SH NOTES
None
.SH VERSION
0.0.1
.SH KEYWORDS
go, auto, format
