.TH YED-ADD_TEMPLATE 7 "YED Plugin Manuals" "" "YED Plugin Manuals"
.SH NAME
loc_history \- saves cursor location between one use of YED and another.
.SH CONFIGURATION
none
.SH COMMANDS
none
.SH NOTES
.P
The file that this plugin uses to store the cursor locations is ~/.yed/my_loc_hitstory.txt.
.SH VERSION
0.0.1
.SH KEYWORDS
save, location, history, cursor
