.TH YED-MOUSE_FRAME_CONTROL 7 "YED Plugin Manuals" "" "YED Plugin Manuals"
.SH NAME
mouse_frame_control \- allows the user to move and resize frames with the middle mouse button
.SH CONFIGURATION
None
.SH COMMANDS
None
.SH BUFFERS
None
.SH NOTES
.P
Clicking in the lower right corner with the middle button allows the user to drag to resize the frame. Clicking anywhere elese on the frame allows the user to move it.
.SH VERSION
0.0.1
.SH KEYWORDS
middle mouse, click, select, middle, control, move, frame
