.TH YED-MOUSE 7 "YED Plugin Manuals" "" "YED Plugin Manuals"
.SH NAME
mouse \- Gives basic mouse support to yed
.SH CONFIGURATION
.SS mouse-cursor-scroll
Sets whether or not the scrolling affects the cursor or not.
.SS mouse-scroll-num-lines
Sets the number of lines each movent of the scroll wheel moves the cursor.
.SH COMMANDS
None
.SH BUFFERS
None
.SH NOTES
.P
This plugin adds left click support to include selecting a location in a buffer as well as activating a frame. It also allows the user to scrol the buffer. If you double click it will hit enter on the cursor location.
.SH VERSION
0.0.1
.SH KEYWORDS
mouse, click, select, left, support
