.TH YED-PAREN_HL 7 "YED Plugin Manuals" "" "YED Plugin Manuals"
.SH NAME
paren_hl \- Highlight matching parentheses.
.SH CONFIGURATION
.SS paren-hl-max-line-length
When scanning for matching parens, if a line exceeds paren-hl-max-line-length, stop scanning.
.SH COMMANDS
None
.SH BUFFERS
None
.SH NOTES
Uses the "associate" style component.
.SH VERSION
0.0.1
.SH KEYWORDS
highlight, parentheses, match
