.TH YED-SAVE_LAYOUT 7 "YED Plugin Manuals" "" "YED Plugin Manuals"
.SH NAME
save_layout \- Saves the layout of the current frame / buffer configuration to a file.
.SH CONFIGURATION
None
.SH COMMANDS
.SS save-current-yed-layout saves the current frame / buffer configuration to the file my_yed_layout.yedrc in ~/.config/yed.
.SS save-current-yed-layout-local saves the current frame / buffer configuration to the file my_yed_layout.yedrc in the local directory.
.SH BUFFERS
None
.SH NOTES
.P You must add a yedrc-load my_yed_layout.yedrc to your global or local yedrc
.SH VERSION
0.0.1
.SH KEYWORDS
save_layout, frame, special, buffers, layout
