.TH YED-WHENCE_YOU_CAME 7 "YED Plugin Manuals" "" "YED Plugin Manuals"
.SH NAME
whence_you_came \- Focus the previously focused buffer in a frame.
.SH CONFIGURATION
None
.SH COMMANDS
.SS whence-you-came
Focus the buffer that was previously focused in the active frame.
.SH NOTES
None
.SH VERSION
0.0.1
.SH KEYWORDS
buffer,focus,whence,alt,alternate,return,jump,switch
