.TH YED-ALIGN 7 "YED Plugin Manuals" "" "YED Plugin Manuals"
.SH NAME
word_wrap \- Wrap all selected lines to a given number of characters.
.SH CONFIGURATION
None
.SH COMMANDS
.SS word-wrap <int>
Wrap all selected lines to <int> characters.
Most useful for writing prose: preserves paragraphs.
.SH NOTES
None
.SH VERSION
0.0.1
.SH KEYWORDS
word, wrap, prose
