.TH YED-XUL 7 "YED Plugin Manuals" "" "YED Plugin Manuals"
.SH NAME
xul \- A modal editor experience inspired by vim and kakoune. Walking selection, vim-like motions, useful operators.
.SH CONFIGURATION
None
.SH COMMANDS
.SS xul-bind <mode> <keys> <command>
Bind <keys> to <command> when in <mode>.
.SS xul-unbind <mode> <keys>
Unbind <keys> in <mode>.
.SS xul-exit-insert
Leave insert mode and return to normal mode.
.SH BUFFERS
None
.SH NOTES
None
.SH VERSION
0.0.1
.SH KEYWORDS
xul, key, bind, binding, edit, mode, modal, vim, vi, emacs, kakoune
