.TH YED-YPM 7 "YED Plugin Manuals" "" "YED Plugin Manuals"
.SH NAME
ypm \- YED Package Manager
.SH CONFIGURATION
none
.SH COMMANDS
.SS ypm-init
This commnad initializes ypm by grabing all the repositories and setting up the buffers.
This command must be run once before the plugin will work.
.SS ypm-list
This command creates a list view of all available plugins and what thier current status is.
All of the management of the plugins can be done from this gui. Hitting ENTER on a plugin will
pull up a list of commands that can be done on the highlighted plugin. If the Man Page is chosen,
ESC will bring you back.
.SS ypm-install [ template-name ]
This command will install the plugin specified.
.SS ypm-uninstall [ template-name ]
This command will uninstall the plugin specified.
.SS ypm-update [ template-name / ALL ]
This command will update the plugin specified, or all the plugins.
.SH NOTES
.P
Still under development.
.SH VERSION
0.0.1
.SH KEYWORDS
ypm, yed, plugin, manager
